import React from 'react';
import clsx from 'clsx';
import './AcidCodeDisplay.css';

export interface AcidCodeDisplayProps {
    title: string;
    code: string;
    language?: string;
    className?: string;
}

export const AcidCodeDisplay = ({ title, code, language = 'tsx', className }: AcidCodeDisplayProps) => {
    const [copied, setCopied] = React.useState(false);

    const handleCopy = () => {
        navigator.clipboard.writeText(code);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <div className={clsx('ac-code-display', className)}>
            <div className="ac-code-display-header">
                <div className="ac-code-display-title">
                    <span className="ac-code-display-dot" />
                    {title}
                </div>
                <button className="ac-code-display-copy" onClick={handleCopy}>
                    {copied ? 'COPIED' : 'COPY'}
                </button>
            </div>
            <div className="ac-code-display-container">
                <pre className="ac-code-display-pre">
                    <code className={`language-${language}`}>{code}</code>
                </pre>
            </div>
            <div className="ac-code-display-footer">
                Generated by <span className="ac-brand-text">ACIDUI</span>
            </div>
        </div>
    );
};
